### ISSUE TITLE
Do you know any GTA based Synthetic dataset for vehicle ReID?

### ISSUE THREAD

**Issue by Xiangyu-CAS** [ndrplz/surround_vehicles_awareness#12]
Hi, I am currently working on vehicle ReID, your project which aims to map front view to bird view seems to be a particular type of ReID. Did you ever generate a vehicle ReID dataset or happens to know one? Thanks!

**Comment by ndrplz** [comment]
Hi @Xiangyu-CAS ,

the dataset underlying this project is called [SVA dataset](https://aimagelab.ing.unimore.it/imagelab/page.asp?IdPage=19) and it was not designed for vehicle Re-ID. However, it can still be used for that purpose as you may use all the bounding boxes of a certain vehicle as it appears in different frames of the ground view as different images of that vehicle. There are many vehicles in the dataset and each one appears for a decent number of frames, so you should be able to get out something useful from there.

Otherwise, if you are comfortable with C++, you may want to build your individual mod to collect the data. In this case, I would recommend taking a look to [this repo](https://github.com/fabbrimatteo/JTA-Mods) to get started.

**Comment by Xiangyu-CAS** [comment]
Thank you for help, may you have a good day : )
