### ISSUE TITLE
filtered dataset

### ISSUE THREAD

**Issue by mirkozaff** [ndrplz/surround_vehicles_awareness#7]
Hi thank you for sharing your dataset, it's amazing! But i was wondering 
if I wanted to collect data other than the distance from of the BBox, how can i then filter the dataset like you did? I'm trying to build a model to predict the speed of vehicles. Thank you!

**Comment by ndrplz** [comment]
Hi @mirkozaff ,
well you just need information about the speed of the vehicles from the current data, you can infer it from the difference of bbox distance between successive frames.

**Comment by mirkozaff** [comment]
Thanks @ndrplz for your reply! Well, not really, becouse to infer information about the speed I need a inertial space and since my car is moving I do not have it.

**Comment by ndrplz** [comment]
Reasonable enough. I guess you may need to collect new data. Unfortunately we cannot release the framework to collect the data from GTA since it is still involved in a [publication](https://arxiv.org/pdf/1803.08319.pdf) under review.

However you may check similar projects like [DeepGTAV](https://github.com/aitorzip/DeepGTAV) to easily get the data you need.

**Comment by mirkozaff** [comment]
Ok I understand no problem, thank you very much for replying me!
